#!/bin/bash

##############
### BASHRC ###
##############

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

if [[ -f ~/.bash_aliases ]]; then
	source ~/.bash_aliases
fi
alias history-edit="edit ~/.bash_history"
