#!/bin/zsh

###################
### ZSH ALIASES ###
###################

# Include bash aliases
if [[ -f ~/.bash_aliases ]]; then
	source ~/.bash_aliases
	alias aliases-edit='conf-edit ~/.bash_aliases ~/.zsh_aliases && aliases-apply'
else
	alias aliases-edit='conf-edit ~/.zsh_aliases && aliases-apply'
fi
alias aliases-apply='echo "✅ applying aliases" && source ~/.zsh_aliases'

# Aliases & Shortcuts & RC-files Management
alias shrc-apply='echo "✅ applying shrc" && start-fg zsh'
# alias shrc-apply="omz reload"
alias shrc-edit="conf-edit ~/.zshrc && shrc-apply"

# Plugin Based Aliases
function aliases { als "$@" | less ;}

# Overrides
if [[ " ${plugins} " =~ " zoxide " ]]; then
	function zo { (z "$@" && files-here ) ;}
	alias j='z'
	alias jo='zo'
elif [[ " ${plugins} " =~ " autojump " ]]; then
	function jo { (j "$@" && files-here ) ;}
	function jco { (jc "$@" && files-here) ;}
	alias z='j'
	alias zo='jo'
else
	alias j='cd'
	alias jo='cdo'
	alias z='cd'
	alias zo='cdo'
fi
