#!/bin/bash

####################
### BASH ALIASES ###
####################

HISTSIZE=1000000000
HISTFILESIZE=1000000000

# Default Flags
alias grep='grep --color=auto'
alias bat='bat --color=always --paging=always --decorations=always'
alias bat-plain='bat --plain --no-paging'
alias code='code -n'
alias sl='sl -acdew8'
alias ip='ip -c a'

# Editing
export EDITOR='micro'
alias edit="${EDITOR}"
alias conf-edit='chezmoi edit --apply'

# Pager
export PAGER='less --ignore-case --quit-on-intr --use-color --wordwrap --raw-control-chars'
export MANPAGER="${PAGER}"
alias pager="${PAGER}"
function pagify { "$@" | pager ;}
alias less="${PAGER} -N"
function lessify { "$@" | less ;}

# Aliases & Shortcuts & RC-files Management
function aliases { alias "$@" | less ;}
function delalias { if alias "$1" > /dev/null 2>&1; then unalias "$1"; fi ;}
alias aliases-apply='echo "✅ applying aliases" && source ~/.bash_aliases'
alias aliases-edit='conf-edit ~/.bash_aliases && aliases-apply'
alias shrc-apply='echo "✅ applying shrc" && start-fg bash'
alias shrc-edit='conf-edit ~/.bashrc && shrc-apply'
alias chezmoi='chezmoi --interactive'
alias chezmoish='start-ntw chezmoi cd'
alias chezmoish-here='start-fg chezmoi cd'
alias config-open='code -n ~/.config'
alias config-open-custom='code -n ~/.config/custom'
function run-source-rm { local temp_file="$(mktemp -u)"; $@ > temp_file && source temp_file; rm -f temp_file ;}
function cd-run { (cd "$1" && "${@:2}") ;}

# Package Management
alias reflector-sync='sudo reflector --protocol https --sort score --save /etc/pacman.d/mirrorlist'
alias reflector-sync-yay='reflector-sync && yay -Syy'
function pacman-search { pacman -Sql | fzf -q "$1" -m --preview 'pacman -Si {1}' ;}
alias pacman-orphans-list='pacman -Qdt'
alias pacman-orphans-list-debug='pacman-orphans-list | grep -E "\-debug\b"'
alias pacman-orphans-remove='pacman -Rs $(pacman -Qdtq)'
alias pacman-orphans-remove-debug='pacman -Rs $(pacman -Qdtq | grep -E "\-debug\b")'
function yay-search { yay -Sql | fzf -q "$1" -m --preview 'yay -Si {1}' ;}
alias yay-orphans-list='yay -Qdt'
alias yay-orphans-list-debug='yay-orphans-list | grep -E "\-debug\b"'
alias yay-orphans-remove='yay -Rs $(yay -Qdtq)'
alias yay-orphans-remove-debug='yay -Rs $(yay -Qdtq | grep -E "\-debug\b")'

# Package Syncronization - Yay
alias yay-pkgs-install='yay -S --needed -< ~/.pkg_list_yay'
alias yay-pkgs-edit='conf-edit ~/.pkg_list_yay'
function yay-pkgs-add { for arg in "$@"; do echo "$arg" >> ~/.pkg_list_yay; done; chezmoi add ~/.pkg_list_yay ;}

# Package Syncronization - Flatpak
alias flatpak-pkgs-install='flatpak install $(cat-xargs ~/.pkg_list_flatpak)'
alias flatpak-pkgs-edit='conf-edit ~/.pkg_list_flatpak'
function flatpak-pkgs-add { for arg in "$@"; do echo "$arg" >> ~/.pkg_list_flatpak; done; chezmoi add ~/.pkg_list_flatpak}

# Power Management
alias sys-sleep='systemctl sleep'
alias sys-suspend='systemctl suspend'
alias sys-hibernate='systemctl hibernate'
alias sys-poweroff='systemctl poweroff'
alias sys-reboot='systemctl reboot'

# System maintenance
alias fastfetch-screen='clear; echo; fastfetch'
alias battery-info='acpi -ba'
alias storage-info='(echo "[ >=> >=> { DUST } <=< <=< ]\n" && sudo dust -C -d 1 / && echo "\n[ >=> >=> { DUF } <=< <=< ]\n" && duf)'
function sysupgrade {
	clear

	bash -c 'read -p "Press Enter to start upgrade for firmware... (ctrl+d to skip)"' \
		|| (echo "\nSkipping" && exit 1) \
		&& echo "-- Upgrading firmware..." \
		&& start-ntw --hold fwupdmgr update

	echo "\n"

	bash -c 'read -p "Press Enter to start upgrade for yay packages... (ctrl+d to skip)"' \
		|| (echo "\nSkipping" && exit 1) \
		&& echo "-- Upgrading yay packages..." \
		&& reflector-sync \
		&& start-ntw --hold yay -Syyu

	echo "\n"

	bash -c 'read -p "Press Enter to start upgrade for flatpak packages... (ctrl+d to skip)"' \
		|| (echo "\nSkipping" && exit 1) \
		&& echo "-- Upgrading flatpak packages..." \
		&& start-ntw --hold flatpak update

	echo "\n"

	bash -c 'read -p "Press Enter to start reboot... (ctrl+d to skip)"' \
		|| (echo "\nSkipping" && exit 1) \
		&& echo "-- Rebooting..." \
		&& sys-reboot
}

# Docs Navigation
function help { "$@" --help 2>&1 | less ;}
function tldr { local target="${@:-tldr}"; command tldr -m "${target}" | bat-plain --language=markdown | less ;}
function cheatsheet { cht.sh "$@" | less -n ;}
function cheatshell { start-bg kitty cht.sh --shell "$1" ;}

# Navigation
alias eza='eza --color=always --classify=always --icons=always --header'
function cdo { (cd "$@" && files-here ) ;}
alias l='ls -l'
alias la='ls -la'
alias ls='eza -g'
alias lsa='ls -a'
alias lD='ls -lD'
alias lDa='ls -lDa'
alias lF='ls -lf'
alias lFa='ls -lfa'
alias lr='l -RT'
alias lar='la -RT'
alias lsr='ls -RT'
alias lsar='lsa -RT'
alias lDr='lD -RT'
alias lDar='lDa -RT'
alias lFr='lF -RT'
alias lFar='lFa -RT'
delalias lDD # using 'lDa' alias instead
delalias lS # unused
delalias lT # unused
delalias ldot # unused
delalias ll # obsolete due to '--header' in 'eza' alias
delalias lsd # unused
delalias lsdl # unused

# Git
alias lzgit='lazygit'
alias gdh='git diff HEAD'

# Periodic Execution
alias watch='watch -n 1 ' # The space at the end enables using aliases
alias watch-f='watch -n 0.1 ' # The space at the end enables using aliases
alias watch-s='watch -n 10 ' # The space at the end enables using aliases

# Text Transformation
alias lowercase="awk '{print tolower(\$0)}'"
alias uppercase="awk '{print toupper(\$0)}'"

# Misc / Utils
function start-bg { (nohup "$@" > /dev/null &) 2> /dev/null ;}
function start-fg { "$@"; exit 2> /dev/null ;}
function start-ntw { start-bg kitty "$@" ;}
alias terminal-here='start-ntw && exit'
alias wait-for-continue="bash -c 'read -p \"Press Enter to continue...\"'"
function files-here { start-bg dolphin --new-window . ;}
function copyfile { cat "$@" | wl-copy ;}
function copypath { pwd "$@" | wl-copy ;}
alias history-l="history | less -n"
function has-cli { if which "$1" > /dev/null 2>&1 && return 0 || return 1 ;}
function cat-xargs { cat "$1" | xargs echo ;}
alias timestamp='date +"%Y-%m-%d %H:%M:%S"'

# Kitty
if [[ "${TERM}" == "xterm-kitty" ]]; then
	alias clear="printf '\033[3J\033[H\033[2J'"
	alias kitty-current-theme='cat ~/.config/kitty/kitty.conf | grep "# BEGIN_KITTY_THEME" -A 1 | tail -n1 | tail -c+3'
	alias kitty-config='conf-edit ~/.config/kitty/kitty.conf'
fi

# Waybar
if has-cli waybar; then
	alias waybar-start='start-bg waybar'
	alias waybar-kill='pkill waybar'
	alias waybar-restart='waybar-kill; waybar-start'
	alias waybar-toggle='pkill --signal SIGUSR1 waybar'
	alias waybar-reload='pkill --signal SIGUSR2 waybar'
fi

# QuickShell
if has-cli quickshell; then
	alias qs-start='start-bg quickshell'
	alias qs-kill='pkill quickshell'
	alias qs-restart='qs-kill; qs-start'
fi

# Punishments
function punish-sl {
	sl

	if [[ "$#" -eq 0 ]]; then
		echo "💢 Whatever it was you just did, it was wrong!"
	elif [[ "$#" -eq 1 ]]; then
		echo "💢 Don't use '$1', it's incorrect!\n💢 Find the correct usage!"
	elif [[ "$#" -ge 2 ]]; then
		local params=""
		if [[ "$#" -ge 3 ]]; then
			params=" ${@:3}"
		fi
		echo -e "💢 Don't use '$1$params' ever again!\n💢 Use '$2$params' instead!"
	fi

	return 1
}
function chezmoid { punish-sl "$0" chezmoi ;}
function cheetsheet { punish-sl "$0" cheatsheet ;}
function cheetshell { punish-sl "$0" cheatshell ;}
function startship-config { punish-sl "$0" starship-config ;}

# Python
alias pyvenv='source .venv/bin/activate && export PATH="$PATH:$(pwd)/.venv/bin" && (uv pip install -e . || exit 0)'
alias pyvenv308='python3.8 -m venv .venv && pyvenv'
alias pyvenv309='python3.9 -m venv .venv && pyvenv'
alias pyvenv312='python3.12 -m venv .venv && pyvenv'
alias pyvenv314='python3.14 -m venv .venv && pyvenv'
alias pyvenvc="pyvenv && echo && wait-for-continue && clear"
alias pyvenvc308='clear && python3.8 -m venv .venv && pyvenvc'
alias pyvenvc309='clear && python3.9 -m venv .venv && pyvenvc'
alias pyvenvc312='clear && python3.12 -m venv .venv && pyvenvc'
alias pyvenvc314='clear && python3.14 -m venv .venv && pyvenvc'
alias rm-pycache='rm -rf ./**/__pycache__; rm -rf ./**/.cache/uv; rm -rf ./**/.cache/ruff; rm -rf ./**/.cache/mypy; rm -rf ./**/.cache/pytest; rm -rf ./**/.uv_cache; rm -rf ./**/.ruff_cache; rm -rf ./**/.mypy_cache; rm -rf ./**/.pytest_cache'
alias rm-pyvenv='deactivate; rm -rf ./**/.venv; rm-pycache'
