#!/bin/zsh

#############
### ZSHRC ###
#############

plugins=(
	"aliases"
	"chezmoi"
	"colored-man-pages"
	"colorize"
	"dirhistory"
	"extract"
	"eza"
	"fzf"
	"git"
	# "git-escape-magic" # disabled because it might not be needed, may enable later
	"git-extras"
	"gh"
	"httpie"
	"kitty"
	"safe-paste"
	"starship"
	"urltools"
	"zoxide"
	"zsh-interactive-cd"
	"zsh-navigation-tools"
)

installed_plugins_dir="/usr/share/zsh/plugins/"
plugins_to_init=(
)
plugins_to_source=(
	"${installed_plugins_dir}zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
	"${installed_plugins_dir}fzf-tab-git/fzf-tab.plugin.zsh"
)

export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="${ZSH}/custom"

CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"

ENABLE_CORRECTION="false"
# COMPLETION_WAITING_DOTS="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"

export FZF_DEFAULT_OPTS_FILE="$HOME/.fzfrc"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' frequency 7

zstyle ':fzf-tab:*' fzf-pad 10
zstyle ':fzf-tab:*' fzf-min-height 20

zstyle ':completion:*:git-checkout:*' sort false
# zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:*' fzf-flags --color='fg:1,fg+:2' --bind='tab:accept'
# zstyle ':fzf-tab:*' use-fzf-default-opts yes
zstyle ':fzf-tab:*' switch-group '<' '>'
zstyle ':autocomplete:tab:*' completion fzf

source $ZSH/oh-my-zsh.sh
for plugin in "${plugins_to_init[@]}"; do
	eval "$(${plugin} init zsh)"
done
for plugin in "${plugins_to_source[@]}"; do
	source "${plugin}"
done

if [[ -f ~/.zsh_aliases ]]; then
	source ~/.zsh_aliases
fi
alias history-edit="edit ~/.zsh_history"
